import { cpSync, rmSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { type Plugin, defineConfig, loadEnv } from "vite";
import { generateLlmsOutput } from "./scripts/build-llms";
import { resolveVersion } from "./scripts/version";

const here = fileURLToPath(new URL(".", import.meta.url));

/**
 * Vite's publicDir must exist before startup, and the LLM output is generated
 * separately, so each build assembles a single served directory here:
 * the checked-in `public/` assets plus the generated Markdown.
 */
const SERVED_DIR = resolve(here, ".build-public");

function prepareServedDir(): void {
  rmSync(SERVED_DIR, { recursive: true, force: true });
  cpSync(resolve(here, "public"), SERVED_DIR, { recursive: true });
}

const SITE_NAME = "dottod docs";
const SITE_DESCRIPTION =
  "Rebuild a Debian workstation with one plain-bash command. Tasks, guides, and reference for dottod.";

/**
 * Injects branding/OG values into index.html. The Open Graph image is
 * always `og-image.png` (generated by `scripts/og-image.ts`).
 */
function brandingPlugin(siteUrl: string): Plugin {
  return {
    name: "dottod-branding",
    transformIndexHtml(html) {
      return html
        .replaceAll("%SITE_NAME%", SITE_NAME)
        .replaceAll("%SITE_DESCRIPTION%", SITE_DESCRIPTION)
        .replaceAll("%SITE_URL%", siteUrl.replace(/\/$/, ""))
        .replaceAll(
          "%VITE_BASE_PATH%",
          process.env.VITE_BASE_PATH ?? "/dottod/",
        );
    },
  };
}

export default defineConfig(({ mode }) => {
  loadEnv(mode, process.cwd(), "");
  const siteUrl =
    process.env.VITE_SITE_URL ?? "https://docs.lucasvmigotto.me/dottod";

  // Generated Markdown lands in the served dir before copying it in.
  prepareServedDir();
  generateLlmsOutput(SERVED_DIR);

  return {
    // Deployed under the docs-hub prefix /dottod/. CI sets VITE_BASE_PATH
    // from the repository name; the local default keeps `vite preview`
    // and e2e at the same path as production.
    base: process.env.VITE_BASE_PATH ?? "/dottod/",
    publicDir: SERVED_DIR,
    plugins: [react(), tailwindcss(), brandingPlugin(siteUrl)],
    define: {
      __APP_VERSION__: JSON.stringify(resolveVersion()),
      __SITE_URL__: JSON.stringify(siteUrl),
    },
    build: {
      outDir: "dist",
      sourcemap: false,
    },
  };
});
